USE Prac;
CREATE TABLE TRANSACTIONS(TransactionsID int,Name varchar(70),Age int);
INSERT INTO TRANSACTIONS VALUES(1,'Sree',21);
INSERT INTO TRANSACTIONS VALUES(2,'Siva',10);

SELECT *FROM TRANSACTIONS;
/*We can rollback only those that have been run after begin transaction*/
BEGIN TRANSACTION;
INSERT INTO TRANSACTIONS VALUES(4,'SS',12343);
SAVE TRANSACTION save1;
INSERT INTO TRANSACTIONS VALUES(45678,'SS',12343);
DELETE FROM TRANSACTIONS WHERE TransactionsID=4;
ROLLBACK TRANSACTION save1;
COMMIT TRANSACTION;